### ISSUE TITLE
add blast

### ISSUE THREAD

**Issue by ghost** [Xeoncross/go-embeddable-stores#2]
this is a great list. I think i have tried almost of of those db's :)

Benchmarking golang DB's is really useful to find what type you need for what work set.

I was wondering if you want to add Blast 
Its a wrapper of bleve.
its not my baby but its been great

https://github.com/mosuka/blast

**Comment by xeoncross** [comment]
Thanks for sharing, Blast isn't an embedded database though. It's a wrapper around Bleve which uses BoltDB. I will mention Blast under the BoltDB tooling. The fact Blast uses Raft is a great addition for larger uses cases like TiDB might have.
